# Generated by Django 2.2.6 on 2019-11-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated')),
                ('color', models.CharField(max_length=20)),
                ('lic', models.CharField(max_length=20)),
                ('style', models.CharField(choices=[('suv', 'SUV'), ('sed', 'Sedan'), ('coup', 'Coupe'), ('semi', 'Semi'), ('pick', 'Pickup'), ('moto', 'Motorcycle'), ('bus', 'Bus')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
