# Generated by Django 2.2.6 on 2019-11-10 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='lic',
        ),
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CarPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amber.Car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
